#pragma once
#include <dxgiformat.h>

MY_LIB_NAMESPACE_BEGIN

struct MODEL_INPUT_LAYOUT_ELEMENT
{
	const char* SemanticName = nullptr;
	DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN;
};

// モデルの入力レイアウトのタイプを以下に記述
enum MODEL_INPUT_LAYOUT_TYPE
{
	MODEL_INPUT_LAYOUT_TYPE_NONE = 0,		// 無効
	MODEL_INPUT_LAYOUT_TYPE_SIMPLE,			// SIMPLE

	MODEL_INPUT_LAYOUT_TYPE_NUM
};

// 入力レイアウトの要素を以下に記述
static const MODEL_INPUT_LAYOUT_ELEMENT INPUT_ELEMENT_POSITION = { "POSITION", DXGI_FORMAT_R32G32B32_FLOAT};
static const MODEL_INPUT_LAYOUT_ELEMENT INPUT_ELEMENT_COLOR = { "COLOR", DXGI_FORMAT_R32G32B32A32_FLOAT};

// モデルの入力レイアウトを以下に記述
static const MODEL_INPUT_LAYOUT_ELEMENT MODEL_INPUT_ELEMENT_SINPLE[] =
{
	INPUT_ELEMENT_POSITION, INPUT_ELEMENT_COLOR 
};

MY_LIB_NAMESPACE_END
